package scanner

import "regexp"

// GetAllRules returns all security detection rules with compiled regex patterns
func GetAllRules() []Rule {
	rules := []Rule{
		// ═══════════════════════════════════════════════════════════════
		// SQL Injection (OWASP A03:2021 - Injection)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "SQL-001",
			Category:       "SQL Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)mysql_query\s*\(\s*["'].*\$`),
			Description:    "Direct variable interpolation in mysql_query string",
			Recommendation: "Use prepared statements with parameterized queries (PDO or mysqli)",
			CWE:            "CWE-89",
		},
		{
			ID:             "SQL-002",
			Category:       "SQL Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)mysql_query\s*\(\s*\$`),
			Description:    "Variable passed directly to mysql_query",
			Recommendation: "Use prepared statements with parameterized queries (PDO or mysqli)",
			CWE:            "CWE-89",
		},
		{
			ID:             "SQL-003",
			Category:       "SQL Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)mysqli_query\s*\(.*\..*\$_(GET|POST|REQUEST|COOKIE)`),
			Description:    "User input concatenated in mysqli_query",
			Recommendation: "Use mysqli prepared statements with bind_param()",
			CWE:            "CWE-89",
		},
		{
			ID:             "SQL-004",
			Category:       "SQL Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)->query\s*\(\s*["'].*\..*\$`),
			Description:    "String concatenation in PDO/mysqli query method",
			Recommendation: "Use PDO::prepare() with placeholders and execute() with bound parameters",
			CWE:            "CWE-89",
		},
		{
			ID:             "SQL-005",
			Category:       "SQL Injection",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)->query\s*\(\s*\$[a-zA-Z_][a-zA-Z0-9_]*\s*\)`),
			Description:    "Variable passed directly to query() method (review source)",
			Recommendation: "Use prepared statements instead of passing variables to query()",
			CWE:            "CWE-89",
		},
		{
			ID:             "SQL-006",
			Category:       "SQL Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(SELECT|INSERT|UPDATE|DELETE|DROP)\s.*\..*\$_(GET|POST|REQUEST)`),
			Description:    "SQL keyword with user input concatenation",
			Recommendation: "Never concatenate user input into SQL queries; use parameterized queries",
			CWE:            "CWE-89",
		},
		{
			ID:             "SQL-007",
			Category:       "SQL Injection",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)mysql_real_escape_string`),
			Description:    "Deprecated mysql_real_escape_string (use prepared statements)",
			Recommendation: "Replace with prepared statements; mysql_* functions are removed in PHP 7+",
			CWE:            "CWE-89",
		},
		{
			ID:             "SQL-008",
			Category:       "SQL Injection",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)addslashes\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "addslashes used for SQL escaping (insufficient protection)",
			Recommendation: "addslashes is NOT safe for SQL; use prepared statements with bound parameters",
			CWE:            "CWE-89",
		},

		// ═══════════════════════════════════════════════════════════════
		// Cross-Site Scripting / XSS (OWASP A03:2021 - Injection)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "XSS-001",
			Category:       "Cross-Site Scripting",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)echo\s+\$_(GET|POST|REQUEST|COOKIE)`),
			Description:    "Direct echo of user input without sanitization",
			Recommendation: "Use htmlspecialchars($input, ENT_QUOTES, 'UTF-8') before output",
			CWE:            "CWE-79",
		},
		{
			ID:             "XSS-002",
			Category:       "Cross-Site Scripting",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)print\s+\$_(GET|POST|REQUEST|COOKIE)`),
			Description:    "Direct print of user input without sanitization",
			Recommendation: "Use htmlspecialchars($input, ENT_QUOTES, 'UTF-8') before output",
			CWE:            "CWE-79",
		},
		{
			ID:             "XSS-003",
			Category:       "Cross-Site Scripting",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`<\?=\s*\$_(GET|POST|REQUEST)`),
			Description:    "Short echo tag outputting user input directly",
			Recommendation: "Use <?= htmlspecialchars($input, ENT_QUOTES, 'UTF-8') ?>",
			CWE:            "CWE-79",
		},
		{
			ID:             "XSS-004",
			Category:       "Cross-Site Scripting",
			Severity:       SeverityLow,
			Pattern:        regexp.MustCompile(`(?i)echo\s+["']?[^;]*\$[a-zA-Z_][a-zA-Z0-9_]*\s*[^;]*;`),
			Description:    "Echo of variable without visible sanitization (review context)",
			Recommendation: "Ensure all echoed variables are sanitized with htmlspecialchars()",
			CWE:            "CWE-79",
		},
		{
			ID:             "XSS-005",
			Category:       "Cross-Site Scripting",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)innerHTML\s*=.*\$_(GET|POST|REQUEST)`),
			Description:    "innerHTML assignment with user input in PHP-generated JavaScript",
			Recommendation: "Use textContent instead of innerHTML, or sanitize with DOMPurify",
			CWE:            "CWE-79",
		},
		{
			ID:             "XSS-006",
			Category:       "Cross-Site Scripting",
			Severity:       SeverityInfo,
			Pattern:        regexp.MustCompile(`(?i)htmlspecialchars\s*\([^)]*ENT_COMPAT`),
			Description:    "htmlspecialchars with ENT_COMPAT (does not escape single quotes)",
			Recommendation: "Use ENT_QUOTES instead of ENT_COMPAT to also escape single quotes",
			CWE:            "CWE-79",
		},
		{
			ID:             "XSS-007",
			Category:       "Cross-Site Scripting",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)document\.write\s*\(.*\$`),
			Description:    "document.write with PHP variable (DOM-based XSS risk)",
			Recommendation: "Avoid document.write; use DOM methods with proper encoding",
			CWE:            "CWE-79",
		},

		// ═══════════════════════════════════════════════════════════════
		// Command Injection (OWASP A03:2021 - Injection)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "CMD-001",
			Category:       "Command Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)exec\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "exec() called with user input",
			Recommendation: "Avoid exec() with user input; use escapeshellarg() and whitelist allowed commands",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-002",
			Category:       "Command Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)system\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "system() called with user input",
			Recommendation: "Avoid system() with user input; use escapeshellarg() and whitelist allowed commands",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-003",
			Category:       "Command Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)passthru\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "passthru() called with user input",
			Recommendation: "Avoid passthru() with user input; use escapeshellarg() and whitelist allowed commands",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-004",
			Category:       "Command Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)shell_exec\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "shell_exec() called with user input",
			Recommendation: "Avoid shell_exec() with user input; use escapeshellarg() and whitelist allowed commands",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-005",
			Category:       "Command Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile("`.*\\$_(GET|POST|REQUEST).*`"),
			Description:    "Backtick operator with user input",
			Recommendation: "Never use backtick operator with user input; use escapeshellarg()",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-006",
			Category:       "Command Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)popen\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "popen() called with user input",
			Recommendation: "Avoid popen() with user input; validate and sanitize all arguments",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-007",
			Category:       "Command Injection",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)proc_open\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "proc_open() called with user input",
			Recommendation: "Avoid proc_open() with user input; validate and sanitize all arguments",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-008",
			Category:       "Command Injection",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)(exec|system|passthru|shell_exec|popen|proc_open)\s*\([^)]*\$[a-zA-Z_][a-zA-Z0-9_]*`),
			Description:    "Command execution function with variable argument (review source)",
			Recommendation: "Review command source; use escapeshellarg()/escapeshellcmd() and whitelist commands",
			CWE:            "CWE-78",
		},
		{
			ID:             "CMD-009",
			Category:       "Command Injection",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)(eval|assert)\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "eval()/assert() with user input (code injection)",
			Recommendation: "Never use eval() or assert() with user input; refactor to avoid dynamic code execution",
			CWE:            "CWE-94",
		},

		// ═══════════════════════════════════════════════════════════════
		// File Inclusion - LFI/RFI (OWASP A03:2021 - Injection)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "FI-001",
			Category:       "File Inclusion",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)\b(include|require)(_once)?\s*[\(]\s*\$_(GET|POST|REQUEST)`),
			Description:    "File inclusion with user input (LFI/RFI vulnerability)",
			Recommendation: "Never use user input in include/require; use a whitelist of allowed files",
			CWE:            "CWE-98",
		},
		{
			ID:             "FI-002",
			Category:       "File Inclusion",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)\b(include|require)(_once)?\s*[\(]\s*\$[a-zA-Z_]`),
			Description:    "File inclusion with variable (potential LFI)",
			Recommendation: "Validate file path against a whitelist; use basename() and restrict to a safe directory",
			CWE:            "CWE-98",
		},
		{
			ID:             "FI-003",
			Category:       "File Inclusion",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)\b(include|require)(_once)?\s*[\(]\s*["'].*\..*\$_(GET|POST|REQUEST)`),
			Description:    "File inclusion with concatenated user input",
			Recommendation: "Never concatenate user input into file paths for include/require",
			CWE:            "CWE-98",
		},

		// ═══════════════════════════════════════════════════════════════
		// Path Traversal (OWASP A01:2021 - Broken Access Control)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "PT-001",
			Category:       "Path Traversal",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)file_get_contents\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "file_get_contents with user input (path traversal risk)",
			Recommendation: "Validate and sanitize file paths; use basename() and restrict to a safe directory",
			CWE:            "CWE-22",
		},
		{
			ID:             "PT-002",
			Category:       "Path Traversal",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)fopen\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "fopen with user input (path traversal risk)",
			Recommendation: "Validate and sanitize file paths; use basename() and restrict to a safe directory",
			CWE:            "CWE-22",
		},
		{
			ID:             "PT-003",
			Category:       "Path Traversal",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)unlink\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "unlink (file delete) with user input",
			Recommendation: "Validate file path against whitelist before deletion; never allow user-controlled paths",
			CWE:            "CWE-22",
		},
		{
			ID:             "PT-004",
			Category:       "Path Traversal",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)file_put_contents\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "file_put_contents with user input (arbitrary file write)",
			Recommendation: "Validate and restrict file paths; never allow user-controlled write destinations",
			CWE:            "CWE-22",
		},
		{
			ID:             "PT-005",
			Category:       "Path Traversal",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)readfile\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "readfile with user input (arbitrary file read)",
			Recommendation: "Validate file path against whitelist; use basename() and restrict directory",
			CWE:            "CWE-22",
		},
		{
			ID:             "PT-006",
			Category:       "Path Traversal",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)copy\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "copy() with user input (arbitrary file operation)",
			Recommendation: "Validate source and destination paths; restrict to safe directories",
			CWE:            "CWE-22",
		},
		{
			ID:             "PT-007",
			Category:       "Path Traversal",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)mkdir\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "mkdir with user input (directory creation with user-controlled path)",
			Recommendation: "Validate directory path; prevent traversal sequences like '../'",
			CWE:            "CWE-22",
		},

		// ═══════════════════════════════════════════════════════════════
		// Insecure Deserialization (OWASP A08:2021)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "DESER-001",
			Category:       "Insecure Deserialization",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)unserialize\s*\(.*\$_(GET|POST|REQUEST|COOKIE)`),
			Description:    "unserialize with user input (object injection vulnerability)",
			Recommendation: "Never unserialize user input; use json_decode() or implement allowed_classes",
			CWE:            "CWE-502",
		},
		{
			ID:             "DESER-002",
			Category:       "Insecure Deserialization",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)unserialize\s*\(\s*\$`),
			Description:    "unserialize with variable (review data source)",
			Recommendation: "Verify data source is trusted; prefer json_decode() or use allowed_classes option",
			CWE:            "CWE-502",
		},
		{
			ID:             "DESER-003",
			Category:       "Insecure Deserialization",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)unserialize\s*\(`),
			Description:    "Use of unserialize (prefer json_decode for data exchange)",
			Recommendation: "Consider using json_decode() instead; if unserialize is needed, use allowed_classes",
			CWE:            "CWE-502",
		},

		// ═══════════════════════════════════════════════════════════════
		// SSRF (OWASP A10:2021 - Server-Side Request Forgery)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "SSRF-001",
			Category:       "SSRF",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)curl_setopt.*CURLOPT_URL.*\$_(GET|POST|REQUEST)`),
			Description:    "cURL URL set from user input (SSRF vulnerability)",
			Recommendation: "Validate and whitelist allowed URLs/domains; block internal IP ranges",
			CWE:            "CWE-918",
		},
		{
			ID:             "SSRF-002",
			Category:       "SSRF",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)file_get_contents\s*\(\s*['"]https?://.*\$_(GET|POST|REQUEST)`),
			Description:    "file_get_contents with user-controlled URL (SSRF risk)",
			Recommendation: "Validate and whitelist allowed URLs; block internal network access",
			CWE:            "CWE-918",
		},
		{
			ID:             "SSRF-003",
			Category:       "SSRF",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)curl_init\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "curl_init with user input URL",
			Recommendation: "Validate URLs against a whitelist; block requests to internal networks",
			CWE:            "CWE-918",
		},
		{
			ID:             "SSRF-004",
			Category:       "SSRF",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)curl_setopt.*CURLOPT_URL.*\$`),
			Description:    "cURL URL set from variable (verify URL source)",
			Recommendation: "Ensure URL source is trusted; validate against whitelist if user-influenced",
			CWE:            "CWE-918",
		},

		// ═══════════════════════════════════════════════════════════════
		// Weak Cryptography (OWASP A02:2021 - Cryptographic Failures)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "CRYPTO-001",
			Category:       "Weak Cryptography",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)md5\s*\(.*pass`),
			Description:    "MD5 used for password hashing (cryptographically broken)",
			Recommendation: "Use password_hash() with PASSWORD_BCRYPT or PASSWORD_ARGON2ID",
			CWE:            "CWE-328",
		},
		{
			ID:             "CRYPTO-002",
			Category:       "Weak Cryptography",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)sha1\s*\(.*pass`),
			Description:    "SHA1 used for password hashing (insufficient for passwords)",
			Recommendation: "Use password_hash() with PASSWORD_BCRYPT or PASSWORD_ARGON2ID",
			CWE:            "CWE-328",
		},
		{
			ID:             "CRYPTO-003",
			Category:       "Weak Cryptography",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)\bmd5\s*\(`),
			Description:    "MD5 usage detected (weak for security purposes)",
			Recommendation: "Use SHA-256+ for integrity checks; use password_hash() for passwords",
			CWE:            "CWE-328",
		},
		{
			ID:             "CRYPTO-004",
			Category:       "Weak Cryptography",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)\bsha1\s*\(`),
			Description:    "SHA1 usage detected (weak for security purposes)",
			Recommendation: "Use SHA-256 or SHA-3 for integrity checks; use password_hash() for passwords",
			CWE:            "CWE-328",
		},
		{
			ID:             "CRYPTO-005",
			Category:       "Weak Cryptography",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)\b(rand|mt_rand|srand|mt_srand)\s*\(`),
			Description:    "Insecure random number generator",
			Recommendation: "Use random_int() or random_bytes() for cryptographic randomness",
			CWE:            "CWE-330",
		},
		{
			ID:             "CRYPTO-006",
			Category:       "Weak Cryptography",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)(MCRYPT_MODE_ECB|'ecb'|"ecb")`),
			Description:    "ECB mode encryption (insecure - patterns visible in ciphertext)",
			Recommendation: "Use CBC or GCM mode; prefer openssl_encrypt() with AES-256-GCM",
			CWE:            "CWE-327",
		},
		{
			ID:             "CRYPTO-007",
			Category:       "Weak Cryptography",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)(MCRYPT_DES|MCRYPT_3DES|'des-|"des-)`),
			Description:    "Weak cipher algorithm (DES/3DES)",
			Recommendation: "Use AES-256; prefer openssl_encrypt() with AES-256-GCM",
			CWE:            "CWE-327",
		},
		{
			ID:             "CRYPTO-008",
			Category:       "Weak Cryptography",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)\bmcrypt_`),
			Description:    "mcrypt extension usage (deprecated and removed in PHP 7.2+)",
			Recommendation: "Migrate to openssl_encrypt()/openssl_decrypt()",
			CWE:            "CWE-327",
		},

		// ═══════════════════════════════════════════════════════════════
		// Authentication & Credentials (OWASP A07:2021)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "AUTH-001",
			Category:       "Authentication & Credentials",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)\$[a-zA-Z0-9_]*(password|passwd|pwd)\s*=\s*['"][^'"]{3,}['"]`),
			Description:    "Hardcoded password detected",
			Recommendation: "Store passwords in environment variables or a secrets manager; never hardcode",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-002",
			Category:       "Authentication & Credentials",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(api_key|apikey|api_secret|secret_key)\s*=\s*['"][^'"]{3,}['"]`),
			Description:    "Hardcoded API key or secret",
			Recommendation: "Store API keys in environment variables or a secrets manager; never hardcode",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-003",
			Category:       "Authentication & Credentials",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)session\.use_only_cookies\s*=\s*0`),
			Description:    "Sessions not restricted to cookies only",
			Recommendation: "Set session.use_only_cookies = 1 to prevent session fixation via URL",
			CWE:            "CWE-384",
		},
		{
			ID:             "AUTH-004",
			Category:       "Authentication & Credentials",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)session\.cookie_httponly\s*=\s*(0|false|off)`),
			Description:    "Session cookie without HttpOnly flag",
			Recommendation: "Set session.cookie_httponly = 1 to prevent JavaScript access to session cookies",
			CWE:            "CWE-1004",
		},
		{
			ID:             "AUTH-005",
			Category:       "Authentication & Credentials",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)session\.cookie_secure\s*=\s*(0|false|off)`),
			Description:    "Session cookie without Secure flag",
			Recommendation: "Set session.cookie_secure = 1 to ensure cookies are only sent over HTTPS",
			CWE:            "CWE-614",
		},
		{
			ID:             "AUTH-006",
			Category:       "Authentication & Credentials",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)session_regenerate_id\s*\(\s*\)`),
			Description:    "session_regenerate_id without deleting old session",
			Recommendation: "Use session_regenerate_id(true) to delete old session data",
			CWE:            "CWE-384",
		},
		{
			ID:             "AUTH-007",
			Category:       "Authentication & Credentials",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)\$_COOKIE\s*\[.*(?:password|passwd|pwd|token)`),
			Description:    "Sensitive data stored in or read from cookies",
			Recommendation: "Never store passwords or tokens in cookies; use server-side sessions",
			CWE:            "CWE-312",
		},
		{
			ID:             "AUTH-008",
			Category:       "Authentication & Credentials",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(mysqli_connect|mysql_connect|pg_connect)\s*\([^)]*['"][^'"]+['"].*['"][^'"]+['"].*['"][^'"]+['"]`),
			Description:    "Database connection with hardcoded credentials",
			Recommendation: "Use environment variables for database credentials; never hardcode in source",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-009",
			Category:       "Authentication & Credentials",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(access_token|auth_token|bearer_token|refresh_token)\s*=\s*['"][^'"]{8,}['"]`),
			Description:    "Hardcoded authentication token",
			Recommendation: "Store tokens in environment variables or secure token storage; never hardcode",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-010",
			Category:       "Authentication & Credentials",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(AKIA[0-9A-Z]{16}|aws_secret_access_key\s*=\s*['"][^'"]+['"])`),
			Description:    "AWS credentials detected (access key or secret key)",
			Recommendation: "Use IAM roles or AWS Secrets Manager; never hardcode AWS credentials",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-011",
			Category:       "Authentication & Credentials",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`-----BEGIN\s+(RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----`),
			Description:    "Private key embedded in source code",
			Recommendation: "Store private keys in secure files outside the webroot; use key management services",
			CWE:            "CWE-321",
		},
		{
			ID:             "AUTH-012",
			Category:       "Authentication & Credentials",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)(smtp_pass|smtp_password|mail_password|email_password)\s*=\s*['"][^'"]+['"]`),
			Description:    "Hardcoded SMTP/email password",
			Recommendation: "Store SMTP credentials in environment variables or a secrets manager",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-013",
			Category:       "Authentication & Credentials",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(mysql|pgsql|mongodb|redis)://[^:]+:[^@]+@`),
			Description:    "Database connection string with embedded password",
			Recommendation: "Use environment variables for connection strings; never embed credentials in DSN",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-014",
			Category:       "Authentication & Credentials",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)(client_secret|app_secret|private_key|encryption_key)\s*=\s*['"][^'"]{6,}['"]`),
			Description:    "Hardcoded application secret or encryption key",
			Recommendation: "Store secrets in environment variables or a dedicated secrets manager",
			CWE:            "CWE-798",
		},
		{
			ID:             "AUTH-015",
			Category:       "Authentication & Credentials",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)base64_decode\s*\(\s*['"][A-Za-z0-9+/=]{20,}['"]\s*\)`),
			Description:    "Base64-encoded string decoded inline (possible obfuscated credential)",
			Recommendation: "Review decoded value; if a credential, move to environment variables",
			CWE:            "CWE-798",
		},

		// ═══════════════════════════════════════════════════════════════
		// Secret Scanning (Extended Credential Detection)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "SECRET-001",
			Category:       "Secret Scanning",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(jwt_secret|jwt_key|JWT_SECRET)\s*[=:]\s*['"][^'"]{8,}['"]`),
			Description:    "Hardcoded JWT secret key",
			Recommendation: "Store JWT secrets in environment variables; rotate keys regularly",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-002",
			Category:       "Secret Scanning",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(sk_live_|sk_test_|pk_live_|pk_test_|rk_live_|rk_test_)[a-zA-Z0-9]{20,}`),
			Description:    "Stripe API key detected",
			Recommendation: "Remove Stripe keys from source code; use environment variables",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-003",
			Category:       "Secret Scanning",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(SG\.)[a-zA-Z0-9_-]{22,}\.[a-zA-Z0-9_-]{20,}`),
			Description:    "SendGrid API key detected",
			Recommendation: "Remove SendGrid keys from source code; use environment variables",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-004",
			Category:       "Secret Scanning",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)(twilio|mailgun|sendgrid|slack|discord|telegram)_?(api_?key|token|secret|webhook)\s*[=:]\s*['"][^'"]{8,}['"]`),
			Description:    "Third-party service API key/token hardcoded",
			Recommendation: "Store third-party API credentials in environment variables or a secrets manager",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-005",
			Category:       "Secret Scanning",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)(google_api_key|gcp_api_key|firebase_api_key|maps_api_key)\s*[=:]\s*['"][^'"]{10,}['"]`),
			Description:    "Google/GCP API key hardcoded",
			Recommendation: "Use environment variables or GCP Secret Manager for API keys",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-006",
			Category:       "Secret Scanning",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)(DB_PASSWORD|DATABASE_PASSWORD|MYSQL_PASSWORD|POSTGRES_PASSWORD|DB_PASS)\s*[=:]\s*['"][^'"]{3,}['"]`),
			Description:    "Hardcoded database password in configuration",
			Recommendation: "Use environment variables for database passwords; never commit credentials",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-007",
			Category:       "Secret Scanning",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)(//|#|/\*)\s*.*(password|secret|token|api.?key|credential)\s*(is|=|:)\s*\S{4,}`),
			Description:    "Sensitive information possibly disclosed in code comment",
			Recommendation: "Remove credentials from comments; comments may be visible in version control history",
			CWE:            "CWE-615",
		},
		{
			ID:             "SECRET-008",
			Category:       "Secret Scanning",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`AIza[0-9A-Za-z_-]{35}`),
			Description:    "Google API key detected (AIza pattern)",
			Recommendation: "Remove API key from source code; use environment variables and restrict key scope",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-009",
			Category:       "Secret Scanning",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`ghp_[0-9A-Za-z]{36}|github_pat_[0-9A-Za-z_]{22,}`),
			Description:    "GitHub personal access token detected",
			Recommendation: "Remove GitHub token from source code; use environment variables",
			CWE:            "CWE-798",
		},
		{
			ID:             "SECRET-010",
			Category:       "Secret Scanning",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`xox[bpras]-[0-9A-Za-z-]{10,}`),
			Description:    "Slack token detected",
			Recommendation: "Remove Slack token from source code; use environment variables",
			CWE:            "CWE-798",
		},

		// ═══════════════════════════════════════════════════════════════
		// Information Disclosure (OWASP A01:2021)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "INFO-001",
			Category:       "Information Disclosure",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)phpinfo\s*\(`),
			Description:    "phpinfo() call exposes server configuration details",
			Recommendation: "Remove phpinfo() from production code; restrict to development environments",
			CWE:            "CWE-200",
		},
		{
			ID:             "INFO-002",
			Category:       "Information Disclosure",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)error_reporting\s*\(\s*E_ALL`),
			Description:    "Verbose error reporting enabled",
			Recommendation: "Use error_reporting(0) in production; log errors to file instead",
			CWE:            "CWE-209",
		},
		{
			ID:             "INFO-003",
			Category:       "Information Disclosure",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)display_errors\s*=\s*(On|1|true|'On'|"On")`),
			Description:    "Display errors enabled (exposes internal details to users)",
			Recommendation: "Set display_errors = Off in production; use log_errors = On instead",
			CWE:            "CWE-209",
		},
		{
			ID:             "INFO-004",
			Category:       "Information Disclosure",
			Severity:       SeverityLow,
			Pattern:        regexp.MustCompile(`(?i)var_dump\s*\(`),
			Description:    "var_dump in code (debug artifact)",
			Recommendation: "Remove var_dump() from production code; use proper logging",
			CWE:            "CWE-200",
		},
		{
			ID:             "INFO-005",
			Category:       "Information Disclosure",
			Severity:       SeverityLow,
			Pattern:        regexp.MustCompile(`(?i)print_r\s*\(`),
			Description:    "print_r in code (debug artifact)",
			Recommendation: "Remove print_r() from production code; use proper logging",
			CWE:            "CWE-200",
		},
		{
			ID:             "INFO-006",
			Category:       "Information Disclosure",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)(debug|DEBUG)\s*=\s*(true|1|'true'|"true")`),
			Description:    "Debug mode enabled",
			Recommendation: "Disable debug mode in production; use environment-specific configuration",
			CWE:            "CWE-200",
		},
		{
			ID:             "INFO-007",
			Category:       "Information Disclosure",
			Severity:       SeverityLow,
			Pattern:        regexp.MustCompile(`(?i)(TODO|FIXME|HACK|XXX|BUG)\b`),
			Description:    "Code annotation suggests incomplete or problematic code",
			Recommendation: "Review and resolve all TODO/FIXME/HACK annotations before production deployment",
			CWE:            "CWE-200",
		},

		// ═══════════════════════════════════════════════════════════════
		// File Upload Vulnerabilities (OWASP A04:2021 - Insecure Design)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "UPLOAD-001",
			Category:       "File Upload",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)move_uploaded_file\s*\(`),
			Description:    "File upload handler detected -- verify file type validation",
			Recommendation: "Validate file extension, MIME type (via finfo), and size; store outside webroot",
			CWE:            "CWE-434",
		},
		{
			ID:             "UPLOAD-002",
			Category:       "File Upload",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)\$_FILES\s*\[.*\]\s*\[\s*['"]name['"]\s*\]`),
			Description:    "User-controlled upload filename used",
			Recommendation: "Never use original filename; generate a random name and validate extension",
			CWE:            "CWE-434",
		},
		{
			ID:             "UPLOAD-003",
			Category:       "File Upload",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)\$_FILES\s*\[.*\]\s*\[\s*['"]type['"]\s*\]`),
			Description:    "Client-supplied MIME type used (can be spoofed)",
			Recommendation: "Use finfo_file() or mime_content_type() for server-side MIME detection",
			CWE:            "CWE-434",
		},
		{
			ID:             "UPLOAD-004",
			Category:       "File Upload",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)copy\s*\(.*\$_FILES`),
			Description:    "File copy from upload without proper validation",
			Recommendation: "Use move_uploaded_file() with validation; never use copy() for uploads",
			CWE:            "CWE-434",
		},

		// ═══════════════════════════════════════════════════════════════
		// CSRF (OWASP A01:2021 - Broken Access Control)
		// Note: CSRF-001 is a multi-line check handled in scanner.go (checkCSRFForm)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "CSRF-001",
			Category:       "CSRF",
			Severity:       SeverityLow,
			Pattern:        regexp.MustCompile(`(?i)<form[^>]*method\s*=\s*['"]post['"][^>]*>`),
			Description:    "POST form without visible CSRF token (review context)",
			Recommendation: "Include a CSRF token in all POST forms; validate token on the server side",
			CWE:            "CWE-352",
		},

		// ═══════════════════════════════════════════════════════════════
		// Open Redirect (OWASP A01:2021 - Broken Access Control)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "REDIR-001",
			Category:       "Open Redirect",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)header\s*\(\s*['"]Location:\s*.*\$_(GET|POST|REQUEST)`),
			Description:    "Open redirect via user input in Location header",
			Recommendation: "Validate redirect URLs against a whitelist of allowed destinations",
			CWE:            "CWE-601",
		},
		{
			ID:             "REDIR-002",
			Category:       "Open Redirect",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)header\s*\(\s*['"]Location:\s*.*\$`),
			Description:    "Redirect with variable URL (verify source is trusted)",
			Recommendation: "Ensure redirect URL is from a trusted source; validate against whitelist",
			CWE:            "CWE-601",
		},

		// ═══════════════════════════════════════════════════════════════
		// XXE - XML External Entity (OWASP A05:2021)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "XXE-001",
			Category:       "XXE",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)simplexml_load_string\s*\(.*\$`),
			Description:    "XML parsing with variable input (XXE risk)",
			Recommendation: "Disable external entities: libxml_disable_entity_loader(true) before parsing",
			CWE:            "CWE-611",
		},
		{
			ID:             "XXE-002",
			Category:       "XXE",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)(DOMDocument|DomDocument).*loadXML\s*\(.*\$`),
			Description:    "DOMDocument XML loading with variable input",
			Recommendation: "Disable external entities and set LIBXML_NONET flag",
			CWE:            "CWE-611",
		},
		{
			ID:             "XXE-003",
			Category:       "XXE",
			Severity:       SeverityCritical,
			Pattern:        regexp.MustCompile(`(?i)libxml_disable_entity_loader\s*\(\s*false\s*\)`),
			Description:    "External entity loader explicitly enabled (XXE vulnerability)",
			Recommendation: "Set libxml_disable_entity_loader(true) to prevent XXE attacks",
			CWE:            "CWE-611",
		},
		{
			ID:             "XXE-004",
			Category:       "XXE",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)simplexml_load_file\s*\(.*\$_(GET|POST|REQUEST)`),
			Description:    "XML file loading with user-controlled path",
			Recommendation: "Validate file path; disable external entities before loading XML",
			CWE:            "CWE-611",
		},
		{
			ID:             "XXE-005",
			Category:       "XXE",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)LIBXML_NOENT`),
			Description:    "LIBXML_NOENT flag enables entity substitution (XXE risk)",
			Recommendation: "Avoid LIBXML_NOENT; process entities only from trusted XML sources",
			CWE:            "CWE-611",
		},

		// ═══════════════════════════════════════════════════════════════
		// Insecure Configuration (OWASP A05:2021 - Security Misconfiguration)
		// ═══════════════════════════════════════════════════════════════
		{
			ID:             "CONFIG-001",
			Category:       "Insecure Configuration",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)allow_url_fopen\s*=\s*(On|1|true)`),
			Description:    "allow_url_fopen enabled (allows remote file access)",
			Recommendation: "Disable allow_url_fopen unless specifically required; use cURL for remote requests",
			CWE:            "CWE-16",
		},
		{
			ID:             "CONFIG-002",
			Category:       "Insecure Configuration",
			Severity:       SeverityHigh,
			Pattern:        regexp.MustCompile(`(?i)allow_url_include\s*=\s*(On|1|true)`),
			Description:    "allow_url_include enabled (enables remote file inclusion)",
			Recommendation: "Always disable allow_url_include; this is a critical security setting",
			CWE:            "CWE-16",
		},
		{
			ID:             "CONFIG-003",
			Category:       "Insecure Configuration",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)register_globals\s*=\s*(On|1|true)`),
			Description:    "register_globals enabled (removed in PHP 5.4, legacy risk)",
			Recommendation: "Upgrade PHP and use $_GET/$_POST superglobals explicitly",
			CWE:            "CWE-16",
		},
		{
			ID:             "CONFIG-004",
			Category:       "Insecure Configuration",
			Severity:       SeverityLow,
			Pattern:        regexp.MustCompile(`(?i)magic_quotes`),
			Description:    "magic_quotes reference (deprecated since PHP 5.3, removed in 5.4)",
			Recommendation: "Remove magic_quotes references; use prepared statements for database queries",
			CWE:            "CWE-16",
		},
		{
			ID:             "CONFIG-005",
			Category:       "Insecure Configuration",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)expose_php\s*=\s*(On|1|true)`),
			Description:    "PHP version exposed in HTTP headers",
			Recommendation: "Set expose_php = Off to hide PHP version from response headers",
			CWE:            "CWE-200",
		},
		{
			ID:             "CONFIG-006",
			Category:       "Insecure Configuration",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)session\.use_trans_sid\s*=\s*(1|On|true)`),
			Description:    "Transparent session ID enabled (session ID in URLs)",
			Recommendation: "Set session.use_trans_sid = 0; session IDs in URLs enable session hijacking",
			CWE:            "CWE-384",
		},
		{
			ID:             "CONFIG-007",
			Category:       "Insecure Configuration",
			Severity:       SeverityMedium,
			Pattern:        regexp.MustCompile(`(?i)session\.cookie_samesite\s*=\s*['"]?(None|none)['"]?`),
			Description:    "Session cookie SameSite set to None",
			Recommendation: "Set session.cookie_samesite = Lax or Strict to prevent CSRF attacks",
			CWE:            "CWE-1275",
		},
	}

	// Append extra rules (Type Juggling, Header Injection, Log Injection, etc.)
	rules = append(rules, GetExtraRules()...)

	return rules
}
